echo -e "MMMMMMMMMMWN0kdolcccccclodk0XWMMMMMMMMMM\n\
MMMMMMWKkl;'..............';lxKWMMMMMMM\n\
MMMMW0o;...........',:odxxdoc;;lONMMMMM\n\
MMMWKo,...........;dO0NMMMMMMWKx:,l0WMMM\n\
MMNk;...........'lKWMMWXOxxkKWMWO:';xNMM\n\
MWx,............cKMMMNx;....,lxkdc,.,xNM\n\
WO;............'dNMMWO,.......;lll:..,kW\n\
Xl.............'dWMWWk,......':lll;...lX\n\
0:........'',;;:kWMMWOc;;,',;clll:,...;O\n\
O;....';::coOXXNWMMMMWNNX0dllllc:'....,O\n\
O;..';clllcoOXXNWMMMMWNNX0dcc:;,......;O\n\
O;.':lllc;,',;;:kWMMWOc;;,''..........cX\n\
O;.;lll:,......'dWMWWk,..............,kW\n\
O;.;lll:'......'xWMWWx'.............,dNM\n\
O;.,cokkl,....,oXMMX0l.............,xNMM\n\
O;..;kNMWKkxxkKWMMXd;'...........'c0WMMM\n\
O,...;xKWWMMMMMWKx:'...........,cONMMMMM\n\
O,.....,codxxdoc,..........';cx0NMMMMMMM\n\
Xo::;;;;;;;:;;;;;;;:;::cldxOXWMMMMMMMMMM\n\
MWXXXXXXXXXXXXXXXXXXXXNNWMMMMMMMMMMMMMMM"
